### PR TITLE
Add --from_builder_dir to uploader.py

### PR DESCRIPTION
**Pull request by jtemple967**
Okay, here's the changes to add the "--from_builder_dir" option to uploader's prepare command.  Note that I handled both single plugin and "all".  The script will overwrite the folder in the uploader path but I assume that's okay since we're copying from builder.

### CODE REVIEW

**Comment by pranciskus** [comment]
@jtemple967 thanks! I think we should either do a separate command for this implementation, e.g. "copy_from_builder_dir" and run "prepare" separately, or don't move/copy the plugins. We could add TARGETS_MAP dict for targets mapping and pass e.g. PLUGINS_DIR to scan_plugins_directory() method. Such overwrites could be painful. Let me know how you want to proceed!

**Comment by jtemple967** [comment]
@pranciskus okay, I'm good with that. I will break out the copy function into a separate command. For consistency sake should the command be a single word of "copy" to match the other commands?

**Comment by pranciskus** [comment]
"copy" sounds good! Much appreciated!

**Comment by jtemple967** [comment]
@pranciskus okay, changes made...I think.  After reading your comments again, I'm not exactly sure what "pass e.g. PLUGINS_DIR to scan_plugins_directory()" meant.  Perhaps you were saying I should use the existing PLUGINS_DIR in the copy function instead of determining where the plugins directory was with my previous commit? That's what I wound up doing instead of reinventing the wheel.

**Comment by pranciskus** [comment]
Merged! Thank you!

**Pull request merged**
